### ISSUE TITLE
How to add "default" newsgroups `local.general` and `local.test`?

### ISSUE THREAD

**Issue by cclauss** [greenbender/inn-docker#1]
`apt-get install --yes inn2` provides eight default newsgroups but this repo only provides six.

On this install the [pynntp](https://github.com/greenbender/pynntp) pytests fail...
> nntp.nntp.NNTPTemporaryError: 411 No such group local.general

```
python3 -m venv .venv
source .venv/bin/activate
pip install pynntp
python
>>> import nntp
>>> with nntp.NNTPClient("localhost") as nntp_client:
...     sorted(nntp_client.list_newsgroups())
[
    ('control', 'Various control messages (no posting).'),
    ('control.cancel', 'Cancel messages (no posting).'),
    ('control.checkgroups', 'Hierarchy check control messages (no posting).'),
    ('control.newgroup', 'Newsgroup creation control messages (no posting).'),
    ('control.rmgroup', 'Newsgroup removal control messages (no posting).'),
    ('junk', 'Unfiled articles (no posting).')
]
```
1. Does pynntp enable admins to create and delete newsgroups?
2. Where in this repo could I add `${PATHBIN}/ctlinnd newgroup local.general y Local` and `${PATHBIN}/ctlinnd newgroup local.test y Local` commands to create the two missing "default" newsgroups?

**Comment by cclauss** [comment]
https://github.com/InterNetNews/inn/blob/main/doc/pod/subscriptions.pod
`/etc/news/subscriptions`
... This is useless.  Modifying `/etc/news/subscriptions` does nothing.

---

In Docker Desktop `exec` into the running container and
~ $ `bin/ctlinnd pause local.general and local.test`
Ok
~ $ `bin/ctlinnd newgroup local.general y Local`
Ok
~ $ `bin/ctlinnd newgroup local.test y Local`
Ok
~ $ `bin/ctlinnd go local.general and local.test`
Ok

This also does nothing.

---

**Comment by greenbender** [comment]
I've added initial `db/` files to do this. These `db/` files are the equivalent of what you have done, but also update `db/newsgroups`.

I used hardcoded files rather than running the commands so we get fixed dates for `db/active.times` and to remove the `.` period from the newsgroup descriptions... and its simple too.

Reference:
https://www.eyrie.org/~eagle/software/inn/docs/newsgroups.html
> If you use ctlinnd newgroup to manually create a group, only the active file is updated. You should then edit the newsgroups file in order to add a short description for the created group. The same goes for manually removing or changing the status of a newsgroup.

**Comment by greenbender** [comment]
Resolved in release https://github.com/greenbender/inn-docker/releases/tag/0.9.0
