### ISSUE TITLE
Using this as a GitHub service container?

### ISSUE THREAD

**Issue by cclauss** [greenbender/inn-docker#2]
The current `apt-get install inn2` approach used to run pynntp pytests is unreliable and fails to install unpredictably.

The approach in this repo seems reliable but has two problems:
1. #1
2. We need to access this container within a GitHub Action.
    * https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers

**Comment by greenbender** [comment]
2 is resolved

```bash
docker pull greenbender/inn
# or
docker pull ghcr.io/greenbender/inn
```
